font_family Terminess Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12
adjust_line_height 100%
adjust_column_width 0
disable_ligatures never
confirm_os_window_close 0
enable_audio_bell no
visual_bell_duration 0
window_padding_width 10
placement_strategy center
remember_window_size yes
initial_window_width 100c
initial_window_height 30c
background_opacity 0.9
dynamic_background_opacity no
cursor_shape beam
cursor_blink_interval 0.5
cursor_stop_blinking_after 15
cursor #53f2f2
cursor_text_color background
selection_background #53f2f2
selection_foreground #0b1020
foreground #f5fbff
background #0b1020
color0 #161d33
color1 #ff6ba3
color2 #5de8b6
color3 #ffd97a
color4 #62a6ff
color5 #b18cff
color6 #53f2f2
color7 #d7e7ff
color8 #49506b
color9 #ff89b8
color10 #82f7ca
color11 #ffe59a
color12 #89beff
color13 #c4a6ff
color14 #83ffff
color15 #ffffff
active_border_color #53f2f2
inactive_border_color #2a355d
bell_border_color #ff5fd7
active_tab_background #53f2f2
active_tab_foreground #0b1020
inactive_tab_background #131b35
inactive_tab_foreground #a8bfdc
tab_bar_background #0b1020
tab_bar_edge top
tab_separator " ┆ "
shell_integration enabled
copy_on_select yes
strip_trailing_spaces smart
hide_window_decorations yes
linux_display_server wayland
mouse_hide_wait 2
scrollback_lines 10000
wheel_scroll_multiplier 5
url_color #53f2f2
url_style curly
open_url_with default
detect_urls yes
allow_remote_control yes
